### ISSUE TITLE
Django Allauth integration

### ISSUE THREAD

**Issue by maver1ck** [PaulleDemon/Django-SAAS-Boilerplate#1]
Hi @PaulleDemon,
It will be great if we can add Django allauth integration to your template.
https://docs.allauth.org/en/latest/index.html

**Comment by PaulleDemon** [comment]
Hey @maver1ck, thanks for your interest, I am actually planning to create a one more boilerplate as soon as this [goal](https://ko-fi.com/artpaul) is reached, upcoming boilerplate will includes, all auth, docker, DRF, websockets and more.  Will notifiy you once its made.

Thanks,
Paul

**Comment by maver1ck** [comment]
Hi @PaulleDemon,
Are you accepting PRs ? 
I will probably do some work on this boilerplate during next week.

DRF sounds like use of React (or any frontend framework).
It will be great to have boilerplate with websockets and htmx :)

**Comment by PaulleDemon** [comment]
Hi @maver1ck, I am accepting PRs, but reviewing it might take sometime. 

About the other boilerplate, it's going to be more customizable. Will let you know about the other one once its done. :)
