### ISSUE TITLE
stripe plans empty

### ISSUE THREAD

**Issue by krajan2** [PaulleDemon/Django-SAAS-Boilerplate#2]
I followed the tutorial on the readme and https://dev.to/paul_freeman/adding-payment-to-django-app-4cc9 (I did not overwrite the Django-SAAS-Boilerplate  html and python code with what was on the link). I set my .env to Debug=1 and created the keys for STRIPE_TEST_API_KEY, STRIPE_PUB_TEST_KEY, and STRIPE_WEBHOOK_TEST_API_KEY using stripe. In stripe I created a product and payment link. I also installed the stripe cli and ran the command:

`stripe listen --forward-to  http://127.0.0.1:8000/stripe/webhook/`

When I go to the  http://127.0.0.1:8000/pricing/ page, I do not see my stripe details populated. Could you please let me know if I am missing a step?

**Comment by PaulleDemon** [comment]
Hi @krajan2, did you add the plan details in the admin panel? you are supposed to add the pricing and comma separated.

![transaction](https://github.com/user-attachments/assets/37374a67-afca-4eac-ba44-16e1118b4456)

**Comment by krajan2** [comment]
Thanks! I thought it pulled product/plan details from stripe.
